<?php
$arrayAnagrafica = [
  [
    "id" => 0,
    "cognome" => "Rossi",
    "nome" => "Mario",
    "data_nascita" => "01-01-1970",
    "luogo_nascita" => "Monfalcone",
    "ral" => 30000,
    "codice_fiscale" => "RSSMRA80A01A01C",
  ],
  [
    "id" => 1,
    "cognome" => "Verdi",
    "nome" => "Giuseppe",
    "data_nascita" => "02-02-1985",
    "luogo_nascita" => "Gorizia",
    "ral" => 40000,
    "codice_fiscale" => "VDRGPP85B02A01A",
  ],
  [
    "id" => 2,
    "cognome" => "Bianchi",
    "nome" => "Anna",
    "data_nascita" => "03-03-1990",
    "luogo_nascita" => "Udine",
    "ral" => 50000,
    "codice_fiscale" => "BIANAA90C03A01C",
  ],
  [
    "id" => 3,
    "cognome" => "Neri",
    "nome" => "Marco",
    "data_nascita" => "04-04-1995",
    "luogo_nascita" => "Trieste",
    "ral" => 60000,
    "codice_fiscale" => "NERMAR95D04A01C",
  ],
  [
    "id" => 4,
    "cognome" => "Gialli",
    "nome" => "Lucia",
    "data_nascita" => "05-05-2000",
    "luogo_nascita" => "Fiumicello",
    "ral" => 55000,
    "codice_fiscale" => "GLLUCC00E05A01C",
  ],
];
